# Base image 
FROM markzwart76/r_reporting

# create directories
RUN mkdir -p /app
RUN mkdir -p /report
RUN mkdir -p /data

## copy files
COPY main.R main.R
COPY make_report.R make_report.R
COPY config.yml config.yml
COPY report.Rmd report.Rmd
